// tailwind.preset.js
module.exports = {
  darkMode: 'media',
  plugins: [
    require('@tailwindcss/typography'),
    require('@tailwindcss/forms'),
    require('@tailwindcss/line-clamp'),
  ],
  theme: {
    colors: {
      'primary-dark': '#003A8C',
      'primary-medium': '#096DD9',
      'primary-light': '#1890FF',
      'secondary-dark': '#006D75',
      'secondary-medium': '#13C2C2',
      'secondary-light': '#5CDBD3',
      black: '#262626',
      'gray-6': '#595959',
      'gray-5': '#BFBFBF',
      'gray-4': '#D9D9D9',
      'gray-3': '#F0F0F0',
      'gray-2': '#F5F5F5',
      'gray-1': '#FAFAFA',
      white: '#ffffff',
      transparent: 'transparent',
      'info-1': '#1890FF',
      'info-2': '#E6F7FF',
      'info-3': '#91D5FF',
      'success-1': '#52C41A',
      'success-2': '#F6FFED',
      'success-3': '#B7EB8F',
      'warning-1': '#FFC53D',
      'warning-2': '#FFFBE6',
      'warning-3': '#FFE58F',
      'error-1': '#F5222D',
      'error-2': '#FFF1F0',
      'error-3': '#FFA39E',
    },
    extend: {},
  },
};
